import fs from 'node:fs';import path from 'node:path';
const root=process.cwd();const required=['index.html','explorer.html','assistant.html','progress.html','review.html','practice-bank.html','lab-v2.html','auth.js','learning.js','lab-bootstrap.js','manifest.webmanifest','service-worker.js','dataset/questions-10000.json'];
const missing=required.filter(f=>!fs.existsSync(path.join(root,f)));if(missing.length){console.error('Missing required files:',missing.join(', '));process.exit(1)}
const html=fs.readdirSync(root).filter(f=>f.endsWith('.html')).map(f=>fs.readFileSync(path.join(root,f),'utf8')).join('\n');
const links=[...html.matchAll(/(?:href|src)=["']([^"'#?]+)(?:["'])/g)].map(m=>m[1]).filter(x=>!/^([a-z]+:|\/|data:|mailto:|javascript:)/i.test(x));
const bad=[...new Set(links)].filter(link=>{const clean=link.replace(/^\.\//,'');return !fs.existsSync(path.join(root,clean))});if(bad.length){console.error('Broken local asset links:',bad);process.exit(1)}
const d=JSON.parse(fs.readFileSync(path.join(root,'dataset/questions-10000.json'),'utf8'));const rows=Array.isArray(d)?d:d.examples;if(!Array.isArray(rows)||rows.length!==10000)throw new Error(`Expected 10000 question records; found ${rows?.length??0}`);
const ids=new Set(),questions=new Set(),dupes=[];const levels=['Easy','Medium','Advanced'];let previous=-1;for(const [i,x] of rows.entries()){for(const k of ['id','difficulty','topic','question','input','output','dataweave','explanation'])if(!String(x?.[k]??'').trim())throw new Error(`Record ${i+1} is missing required ${k}`);if(ids.has(x.id))dupes.push(`ID:${x.id}`);ids.add(x.id);const q=String(x.question).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(questions.has(q))dupes.push(`QUESTION:${x.id}`);questions.add(q);if(!levels.includes(x.difficulty))throw new Error(`Unsupported difficulty at ${x.id}: ${x.difficulty}`);const rank=levels.indexOf(x.difficulty);if(rank<previous)throw new Error(`Difficulty order is not Easy → Medium → Advanced at ${x.id}`);previous=rank;if(!String(x.dataweave).trimStart().startsWith('%dw'))throw new Error(`Invalid DataWeave header at ${x.id}`);const expectedId=`DW-${String(i+1).padStart(5,'0')}`;if(x.id!==expectedId)throw new Error(`Unexpected ID at record ${i+1}: ${x.id}`)}if(dupes.length)throw new Error(`Duplicate IDs/questions: ${dupes.slice(0,20).join(', ')}`);
const files=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(['.git','node_modules'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else if(/\.(html|js|json|md|yml|yaml|txt)$/.test(e.name))files.push(p)}}walk(root);
const external=[];for(const f of files){const text=fs.readFileSync(f,'utf8');for(const m of text.matchAll(/https?:\/\/[^\s"'<>`)]+/g))external.push(`${f}:${m[0]}`)}const official=external.filter(x=>/mulesoft\.com|docs\.mulesoft\.com|help\.mulesoft\.com/i.test(x));if(official.length)throw new Error(`External MuleSoft documentation links are not allowed: ${official.slice(0,20).join(', ')}`);
console.log(`PASS: ${rows.length} records, ${ids.size} unique IDs, ${questions.size} unique questions, ordered difficulty, valid DataWeave headers, ${new Set(links).size} local asset links checked, no external MuleSoft documentation links.`);
